#!/bin/bash

export PATH="$PATH:/opt/blast/bin"

export BLASTDB=/RESTORE/
export GENOMES=/GENOMES/
export PROTOSP=/RESTORE/
export SCRATCH=/data/scratch/


# export APPSESS=/data/input/AppSession.json
export APPSESS=/root/pycrispr/tests/data/AppSession.json

echo

echo BLASTDB is now $BLASTDB
echo GENOMES is now $GENOMES
echo PROTOSP is now $PROTOSP

echo SCRATCH is now $SCRATCH
echo APPSESS is now $APPSESS

echo

cat /APP/hello.txt

echo pip uninstall -y pycrispr
pip uninstall -y pycrispr

echo pip install -e /root/pycrispr/
pip install -e /root/pycrispr/

# echopip install git+https://github.com/alaindomissy/pycrispr.git
# pip install git+https://github.com/alaindomissy/pycrispr.git

# pip install  git+https://github.com/alaindomissy/buffet.git#egg=pycrispr

# pip install primer3-py


/root/miniconda/bin/python -m pybasespace.app
